# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creddit.proto\x12\x06reddit\"\x17\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\xdf\x01\n\x04Post\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x13\n\timage_url\x18\x03 \x01(\tH\x00\x12\x13\n\tvideo_url\x18\x04 \x01(\tH\x00\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x05\x12!\n\x05state\x18\x07 \x01(\x0e\x32\x12.reddit.Post.State\x12\x18\n\x10publication_date\x18\x08 \x01(\t\"+\n\x05State\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06LOCKED\x10\x01\x12\n\n\x06HIDDEN\x10\x02\x42\x07\n\x05media\"\x9a\x01\n\x07\x43omment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x05\x12&\n\x06status\x18\x04 \x01(\x0e\x32\x16.reddit.Comment.Status\x12\x18\n\x10publication_date\x18\x05 \x01(\t\" \n\x06Status\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06HIDDEN\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reddit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=24
  _globals['_USER']._serialized_end=47
  _globals['_POST']._serialized_start=50
  _globals['_POST']._serialized_end=273
  _globals['_POST_STATE']._serialized_start=221
  _globals['_POST_STATE']._serialized_end=264
  _globals['_COMMENT']._serialized_start=276
  _globals['_COMMENT']._serialized_end=430
  _globals['_COMMENT_STATUS']._serialized_start=398
  _globals['_COMMENT_STATUS']._serialized_end=430
# @@protoc_insertion_point(module_scope)
